import fs from "fs";
import path from "path";

import { indexTemplate } from "../templates/base/index.template.js";
import { appTemplate } from "../templates/base/app.template.js";
import { mongoTemplate } from "../templates/db/mongo.template.js";
import { envTemplate } from "../templates/config/env.template.js";
import { utilsTemplates } from "../templates/utils/utils.template.js";

export function createFiles(projectPath, answer) {
    // index.js
    fs.writeFileSync(
        path.join(projectPath,"src", "index.js"),
        indexTemplate(answer)
    );

    // app.js
    fs.writeFileSync(
        path.join(projectPath,"src", "app.js"),
        appTemplate(answer)
    );

    // utils
    Object.entries(utilsTemplates).forEach(([file, content]) => {
        fs.writeFileSync(path.join(projectPath, "src", "utils", file), content);
    });

    // constants
    fs.writeFileSync(
        path.join(projectPath, "src", "constants.js"),
        `export const DB_NAME = "your_db_name";`
    );

    // mongo
    if (answer.useMongo) {
        fs.writeFileSync(
            path.join(projectPath, "src", "db", "connect.js"),
            mongoTemplate()
        );
    }

    // .env
    if (answer.ENV) {
        fs.writeFileSync(path.join(projectPath, ".env"), envTemplate(answer));
    }

    fs.writeFileSync(
        path.join(projectPath, "README.md"),
        `# ${answer.projectName}\n\nGenerated with create-prod-backend CLI. Customize your README to provide instructions and information about your project. \n\n## Setup\n\n1. Install dependencies: \`npm install\`\n2. Start the server: \`npm start\` \n\n## Environment Variables\n\n- \`PORT\`: Port number for the server (default: 3000)\n- \`MONGO_URI\`: MongoDB connection string (if using MongoDB)\n- \`JWT_SECRET\`: Secret key for JWT authentication (if using auth)\n- \`CLOUDINARY_CLOUD_NAME\`, \`CLOUDINARY_API_KEY\`, \`CLOUDINARY_API_SECRET\`: Cloudinary credentials (if using file upload) \n\n## Features\n\n- Express server setup\n- CORS enabled\n- Environment variable support with dotenv\n${answer.auth ? "- JWT authentication with jsonwebtoken and bcrypt\n" : ""}${answer.validation ? "- Request validation with Zod\n" : ""}${answer.fileUpload ? "- File upload handling with Multer and Cloudinary\n" : ""}${answer.devTools ? "- Development tools with Nodemon\n" : ""}${answer.useMongo ? "- MongoDB integration with Mongoose\n" : ""}\n\n## License\n\nThis project is licensed under the ISC License. \n\n---\n\n*Generated by [create-prod-backend](https://www.npmjs.com/package/create-prod-backend)*`
    );

    // gitignore
    fs.writeFileSync(
        path.join(projectPath, ".gitignore"),
        `node_modules/
.env
dist/
coverage/
.DS_Store`
    );
}